### PR TITLE
Fix several issues in mpi_globals.f90

### PR DESCRIPTION
**Pull request by aradi**
* Importing the mpi module explicitly
* Fixing incorrect variable types
* Eliminiating implicitly saved variables

### CODE REVIEW

**Comment by awvwgk** [comment]
Fails with MPICH (both Linux and OSX): 

```
[112/144] Building Fortran object src/CMakeFiles/negf.dir/mpi_globals.f90.o
FAILED: src/CMakeFiles/negf.dir/mpi_globals.f90.o src/include/mpi_globals.mod 
$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-gfortran -Isrc -Iext_system/include -Isrc/include -I$PREFIX/include/mpifx/modfiles -I$PREFIX/include -march=core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/libnegf-1.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 -Jsrc/include -fPIC -fpreprocessed -c src/CMakeFiles/negf.dir/mpi_globals.f90-pp.f90 -o src/CMakeFiles/negf.dir/mpi_globals.f90.o
src/mpi_globals.f90:26:17:

   26 |   use mpi, only : mpi_cart_create, mpi_cart_sub
      |                 1
Error: Symbol ‘mpi_cart_create’ referenced at (1) not found in module ‘mpi’
src/mpi_globals.f90:26:34:

   26 |   use mpi, only : mpi_cart_create, mpi_cart_sub
      |                                  1
Error: Symbol ‘mpi_cart_sub’ referenced at (1) not found in module ‘mpi’

```

**Comment by aradi** [comment]
I've completely forgotten, that MPICH's F90 module contains only a "selection" of all MPI-routines (for whatever reasons). I've fixed this in 344af32, however, it could happen, that it brings back the problem on OSX...

**Comment by awvwgk** [comment]
Trying this right now at https://github.com/conda-forge/libnegf-feedstock/pull/5

**Comment by awvwgk** [comment]
:+1: Seems to work now

**Pull request merged**
